config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  root "todos#index"
  resources :todos do
    member do
      post "toggle_status"
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
  enum status: { 'Not Done': 0, 'Done': 1 }
  validates :title, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.all
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to todos_path, notice: "Todo was created"
    else
      @todos = Todo.all
      render :index
    end
  end

  def destroy
    @todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to todos_path, notice: "Todo deleted"
  end

  def toggle_status
    @todo = Todo.find(params[:id])
    Rails.logger.warn @todo
    @todo.status = @todo.status == "Done" ? "Not Done" : "Done"
    @todo.save
    Rails.logger.warn @todo
    redirect_to todos_path
  end

  private
  def todo_params
    params.require(:todo).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Simple Rails Todo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="turbo-prefetch" content="false">
    <title>Document</title>
</head>
<body>
    <% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

<% if @todo.errors.any? %>
    <% @todo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
    <% end %>
<% end %>

<%= form_with model: @todo, data: {turbo: false} do |form| %>
    <%= form.text_field :title %>
    <%= form.submit %>
<% end %>

<% @todos.each do |todo| %>
    <li><%= todo.title %> | <%= todo.status %> |
        <% if todo.status == 'Not Done' %>
            <%= link_to 'mark done', toggle_status_todo_path(todo), data: {turbo_method: :post} %>
        <% elsif todo.status == 'Done' %>
            <%= link_to 'mark not done', toggle_status_todo_path(todo), data: {turbo_method: :post} %>
        <% end %>
        <%= link_to 'X', todo_path(todo), data: {turbo_method: :delete} %>
    </li>
<% end %>
</body>
</html>